[project]
name = "auth"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13.2"
dependencies = [
    "bcrypt>=4.3.0",
    "dotenv>=0.9.9",
    "fastapi>=0.116.1",
    "jwt>=1.4.0",
    "sqlalchemy>=2.0.41",
]
