services:
  gateway:
    build:
      context: .
      dockerfile: services/gateway/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      preprocessing:
        condition: service_healthy
      sentiment_analysis:
        condition: service_healthy
      summarization:
        condition: service_healthy
    networks:
      - app-network
    environment:
      - PREPROCESSING_SERVICE_URL=http://preprocessing:8000
      - SENTIMENT_SERVICE_URL=http://sentiment_analysis:8000
      - SUMMARIZATION_SERVICE_URL=http://summarization:8000
    
  preprocessing:
    build:
      context: .
      dockerfile: services/preprocessing/Dockerfile
    # No ports exposed - only internal communication
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/health')"]
      retries: 5
      timeout: 5s
      interval: 10s
      start_period: 10s

  sentiment_analysis:
    build:
      context: .
      dockerfile: services/sentiment_analysis/Dockerfile
    # No ports exposed - only internal communication
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/health')"]
      retries: 5
      timeout: 5s
      interval: 10s
      start_period: 60s   # Loading ML model takes some time

  summarization:
    build:
      context: .
      dockerfile: services/summarization/Dockerfile
    # No ports exposed - only internal communication
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/health')"]
      retries: 5
      timeout: 5s
      interval: 10s
      start_period: 60s   # Loading ML model takes some time

  prometheus:
    image:
      prom/prometheus:latest
    ports:
      - "9000:9000"
    volumes:
      - ./services/gateway/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
    
    