services:
  gateway:
    build:
      context: .
      dockerfile: services/gateway/Dockerfile
      target: development
    ports:
      - "8000:8000"
    depends_on:
      preprocessing:
        condition: service_healthy
      sentiment_analysis:
        condition: service_healthy
      summarization:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/health')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - app-network
    env_file:
      - .env
    labels:
      logging: "promtail"
      logging_jobname: "gateway"
    
  preprocessing:
    build:
      context: .
      dockerfile: services/preprocessing/Dockerfile
      target: base
    # No ports exposed - only internal communication
    ports:
      - "8001:8000"  # For local testing
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/health')"]
      retries: 5
      timeout: 5s
      interval: 10s
      start_period: 10s
    env_file:
      - services/preprocessing/.env
    labels:
      logging: "promtail"
      logging_jobname: "preprocessing"
    depends_on:
      prometheus:
        condition: service_healthy
      promtail:
        condition: service_healthy
      loki:
        condition: service_healthy  # Add this if tempo is running
      tempo:
        condition: service_healthy  # Add this if tempo is running
      redis:
        condition: service_healthy

  sentiment_analysis:
    build:
      context: .
      dockerfile: services/sentiment-analysis/Dockerfile
      target: base
    # No ports exposed - only internal communication
    ports:
      - "8002:8000"  # For local testing
    volumes:
      - ./services/sentiment-analysis/models:/opt/models
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/health')"]
      retries: 5
      timeout: 5s
      interval: 10s
      start_period: 60s   # Loading ML model takes some time
    labels:
      logging: "promtail"
      logging_jobname: "sentiment_analysis"

  summarization:
    build:
      context: .
      dockerfile: services/summarization/Dockerfile
      target: development
    # No ports exposed - only internal communication
    volumes:
      - summarization-models:/root/.cache/huggingface
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/health')"]
      retries: 5
      timeout: 5s
      interval: 10s
      start_period: 60s   # Loading ML model takes some time
    networks:
      - app-network
    labels:
      logging: "promtail"
      logging_jobname: "summarization"

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./services/gateway/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:9090/-/healthy"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    networks:
      - app-network

  auth:
    build:
      context: .
      dockerfile: services/auth/Dockerfile
      target: development
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/health')"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    networks:
      - app-network
    labels:
      logging: "promtail"
      logging_jobname: "auth"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"  # For local testing
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru --tcp-keepalive 300
    # Keep tcp connections alive for performance
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M    # safety net, after the limit of 256 set by redis-server
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    networks:
      - app-network

# Loki for log storage
  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    volumes:
      - loki-data:/tmp/loki
    # No command - use built-in default config
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3100/ready"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    networks:
      - app-network

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana-provisioning:/etc/grafana/provisioning
    env_file:
      - services/grafana/.env
    depends_on:
      loki:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/api/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    networks:
      - app-network

  # Promtail for log shipping
  promtail:
    image: grafana/promtail:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./promtail-config.yml:/etc/promtail/config.yml
    # No command - use built-in default config
    ports:
      - "9080:9080"
    depends_on:
      loki:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "promtail", "-version"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 30s
    labels:
      logging: "promtail"
      logging_jobname: "promtail"
    networks:
      - app-network

  tempo:
      image: grafana/tempo:latest
      command: [ "-config.file=/etc/tempo.yaml" ]
      volumes:
        - ./tempo-config.yaml:/etc/tempo.yaml
        - tempo-data:/var/tempo
      ports:
        - "3200:3200"   # tempo
        - "4317:4317"   # otlp grpc
        - "4318:4318"   # otlp http
      healthcheck:
        test: ["CMD", "wget", "-qO-", "http://localhost:3200/ready"]
        interval: 10s
        timeout: 5s
        retries: 3
        start_period: 10s
      networks:
        - app-network

  k6:
    image: grafana/k6:latest
    command: ["run", "/k6-tests/load-test-preprocessing.js"]
    volumes:
      - ./k6-tests:/k6-tests
    depends_on:
      preprocessing:
        condition: service_healthy
      prometheus:
        condition: service_healthy
    env_file:
      - k6-tests/.env
    profiles:
      - load-test  # Only run when explicitly requested
    networks:
      - app-network
    

networks:
  app-network:
    driver: bridge
  
volumes:
  prometheus-data:
  summarization-models:
  sentiment-models:
  loki-data:
  grafana-data:
  tempo-data:
  redis-data:
