apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: your-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: matthieuneau/gateway:1.0.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        env:
        - name: PREPROCESSING_URL
          value: "http://preprocessing-service:8000"
        - name: SENTIMENT_ANALYSIS_URL
          value: "http://sentiment-analysis-service:8000"
        - name: SUMMARIZATION_URL
          value: "http://summarization-service:8000"
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: your-app
spec:
  type: NodePort
  selector:
    app: gateway
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30080