apiVersion: apps/v1
kind: Deployment
metadata:
  name: preprocessing
  namespace: your-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: preprocessing
  template:
    metadata:
      labels:
        app: preprocessing
    spec:
      containers:
      - name: preprocessing
        image: matthieuneau/preprocessing:1.0.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: preprocessing-service
  namespace: your-app
spec:
  selector:
    app: preprocessing
  ports:
  - port: 8000
    targetPort: 8000