apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentiment-analysis
  namespace: your-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sentiment-analysis
  template:
    metadata:
      labels:
        app: sentiment-analysis
    spec:
      containers:
        - name: sentiment-analysis
          image: matthieuneau/sentiment-analysis:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: sentiment-analysis-service
  namespace: your-app
spec:
  selector:
    app: sentiment-analysis
  ports:
    - port: 8000
      targetPort: 8000
