apiVersion: apps/v1
kind: Deployment
metadata:
  name: summarization
  namespace: your-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: summarization
  template:
    metadata:
      labels:
        app: summarization
    spec:
      containers:
      - name: summarization
        image: matthieuneau/summarization:1.0.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: summarization-service
  namespace: your-app
spec:
  selector:
    app: summarization
  ports:
  - port: 8000
    targetPort: 8000